name: Semgrep
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - develop
      - main
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    # random HH:MM to avoid a load spike on GitHub Actions at 00:00
    - cron: '56 22 * * *'
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      #- run: semgrep ci --output /src/semgrep-findings.json --json
      #- run: python /src/semgrep-json-to-sarif.py --json /src/semgrep-findings.json --sarif /src/semgrep-sarif.sarif
      - run: which semgrep
      - run: ls -l
      #- run: semgrep ci --sarif > semgrep.sarif

      #- name: Upload SARIF file for GitHub Advanced Security Dashboard
      #  uses: github/codeql-action/upload-sarif@v3
      #  with:
      #    sarif_file: semgrep.sarif


